---
title: "Fthr_MSSTATS"
author: "Jon"
date: "February 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, cache = TRUE}
#GET THE PARTY STARTED WITH DATA AND LIBRARIES
setwd("D:/jmcmurry/Documents/Davis_data/combined/txt")
rawpeps = read.csv("modificationSpecificPeptides.txt", sep = "\t", row.names = "id")
```

```{r}
###FILTER THE DATA
library("stringr")
allpeps           = rawpeps
#Limit scope to only one Thr/pep.  Cuts # of F-peps down to 500 from 900.
T.Count           = str_count(allpeps$Sequence, "T")
allpeps           = cbind(T.Count, allpeps)
names(allpeps)[1] = "T.Count"
allpeps           = allpeps[allpeps$T.Count ==1,]                     
#Limit scope to fully tryptic peptides.
allpeps          = allpeps[allpeps$Missed.cleavages == 0,]
#Remove hits to decoy and contaminant databases.
allpeps           = allpeps[allpeps$Reverse != "+",]
allpeps           = allpeps[allpeps$Potential.contaminant != "+",]
#Limit scope of analysis to high quality hits.
allpeps           = allpeps[allpeps$PEP <0.01,]						#a less stringent PEP will give ~20% more IDs and ~15% more proteins
#Limit scope of analysis to proteotypic peptides.
allpeps           = allpeps[allpeps$Unique..Proteins. == "yes",]
#Get row means for the pertinent rows and eliminate rows with no measured intensity.
delp0564rows      = c(40,43,44,45)
#names(allpeps)[delp0564rows]
delp0564means     = rowMeans(allpeps[,delp0564rows])
allpeps           = allpeps[ delp0564means > 0 & is.na(delp0564means) == FALSE ,]

###Extract Fthr modified and unmodified peptides.
Fpeps = allpeps[allpeps$Modifications == "Fluorothreonine",] 
Tpeps = allpeps[allpeps$Modifications == "Unmodified",]
```

```{r}
###Qualitative data analysis
mergedPeps = merge(Tpeps, Fpeps, by = "Sequence")# all=TRUE)
mergedPeps[is.na(mergedPeps)] = 0
Trows      = c(40,43,44,45)
Frows      = c(95,98,99,100)
Trows_WT   = c(39,41,42,46)
Frows_WT   = c(94,96,97,101)
Tvec       = c(mergedPeps[,Trows[1]]   , mergedPeps[,Trows[2]]   , mergedPeps[,Trows[3]]   , mergedPeps[,Trows[4]])
Fvec       = c(mergedPeps[,Frows[1]]   , mergedPeps[,Frows[2]]   , mergedPeps[,Frows[3]]   , mergedPeps[,Frows[4]])
Fmeans     = rowMeans(mergedPeps[,Frows])
Tmeans     = rowMeans(mergedPeps[,Trows])
Fmeans_WT  = rowMeans(mergedPeps[,Frows_WT])
Tmeans_WT  = rowMeans(mergedPeps[,Trows_WT])
Tvec_WT    = c(mergedPeps[,Trows_WT[1]], mergedPeps[,Trows_WT[2]], mergedPeps[,Trows_WT[3]], mergedPeps[,Trows_WT[4]])
Fvec_WT    = c(mergedPeps[,Frows_WT[1]], mergedPeps[,Frows_WT[2]], mergedPeps[,Frows_WT[3]], mergedPeps[,Frows_WT[4]])
ratios     = mergedPeps[,Frows]/(mergedPeps[,Frows] + mergedPeps[,Trows]+0.0001)
ratios_WT  = mergedPeps[,Frows_WT]/(mergedPeps[,Frows_WT] + mergedPeps[,Trows_WT]+0.0001)
meanrats   = rowMeans(ratios)
meanrats_WT= rowMeans(ratios_WT)
summary(Fvec/(Fvec + Tvec))
summary(Fvec_WT/(Fvec_WT + Tvec_WT))
#summary(Fmeans/(Fmeans + Tmeans))

pdf("delp0564_Fincorp_hist.pdf", width = 5, height =5)
hist   (meanrats,
        main = "Frequency of Fthr incorporation",
        xlab = "Est. Fthr incorporation", 
        breaks = seq(0,1, by = 0.025), col = 2
               )
box()
dev.off()

pdf("WT_Fincorp_hist.pdf", width = 5, height =5)
hist   (meanrats_WT,
        main = "Frequency of Fthr incorporation",
        xlab = "Est. Fthr incorporation",
        breaks = seq(0,1, by = 0.025), col = "gray"
               )
box()
dev.off()

pdf("scatter_TvF_intens.pdf", width = 5, height = 5)
plot    (Tmeans, Fmeans,
         main = "Intensity of Thr vs. Fthr signal",
         xlab = "Thr intensity",
         ylab = "Fthr intensity",
         ylim = c(1e4, 1e10), xlim = c(1e6, 1e10),
         pch = 16, log = "xy", cex = 0.5, asp = 1, col = 2)
points   (Tmeans_WT, Fmeans_WT,
          pch = 16, cex = 0.5, col = 1)
dev.off()

pdf("RT_comparison.pdf", height = 5, width = 5)
plot(mergedPeps$Retention.time.x, 
     mergedPeps$Retention.time.y,
     pch = 16, cex=.5,
     xlab = "Thr ret. time (min)",
     ylab = "Fth ret.time (min)")
dev.off()   

#plot   (Tmean, Fmean, pch = 16, cex = 0.5, log= "xy")
#plot(density(log(Tmean, base=10)), lwd=2, xlim=c(5,10))
#points(density(log(Fmean, base=10)), col = 2, lwd=2, type = "l")
#plot(Tmean,Fmean/(Fmean+Tmean),pch=16, cex=0.5, log="x")
```


```{r}
library("MSstats")

###Pull out only peptides that are present in both Fthr and Thr forms.
intersect_names     = intersect(Tpeps$Sequence, Fpeps$Sequence)
Fpeps               = Fpeps[Fpeps$Sequence %in% intersect_names,]
Tpeps               = Tpeps[Tpeps$Sequence %in% intersect_names,]
Fpeps[is.na(Fpeps)] = 0
Tpeps[is.na(Tpeps)] = 0

#Define a function to convert Maxquant output into MSstats input.  
parse_MSstats = function(input, cols, cond, protpep) {
tempframe = NULL
for( i in cols) {
  temp                = NULL
  ell                 = length(input[,i])
  samp                = names(input)[i]
  #Weid stuff. Need to distinguish the fluorothreonine "run" from the threonine "run"
  #when they actually originate from the same run.
  run                 = paste(samp, cond, sep = "_")
  if (protpep == "Protein") {
      ProteinName         = input$Proteins 
  }
  if (protpep == "Peptide") {
      ProteinName         = paste(input$Sequence, input$Proteins, sep = "_")
  }
  PeptideSequence     = input$Sequence
  Intensity           = input[,i]
  PrecursorCharge     = input$Charges
  FragmentIon         = rep(NA,     ell)
  ProductCharge       = rep(NA,     ell)
  IsotopeLabelType    = rep("L",    ell)
  Run                 = rep(run,    ell)
  BioReplicate        = rep(samp,   ell)
  Condition           = rep(cond,   ell)
  
  temp                = data.frame(ProteinName, PeptideSequence, 
                                   PrecursorCharge, FragmentIon, 
                                   ProductCharge, IsotopeLabelType, 
                                   Condition, BioReplicate, 
                                   Run, Intensity)
  tempframe           =rbind(temp, tempframe)
}
  return(tempframe)
}

Fprot_format = parse_MSstats(Fpeps, c(40,43,44,45), "Fluorothreonine", "Protein" )
Tprot_format = parse_MSstats(Tpeps, c(40,43,44,45), "Threonine"      , "Protein" )
MSSinput     = rbind(Fprot_format, Tprot_format) 
#quantile seems to give more reasonable distr. of log2FC
FvsTproc     = dataProcess(raw=MSSinput, censoredInt = 0, MBimpute = TRUE, normalization = 'quantile') 
comparison1  = matrix(c(1,-1), nrow=1)
row.names(comparison1) = "AA"
FvsTquant    = groupComparison(contrast.matrix = comparison1, data=FvsTproc)
#pull out only rows for which a comparison could be made, get the fold change and p values.
FvsTres      = FvsTquant$ComparisonResult[is.na(FvsTquant$ComparisonResult$pvalue) == FALSE,]
FC           = FvsTres$log2FC
p            = FvsTres$pvalue
row.names(FvsTres) = FvsTres$Protein
write.csv(FvsTres[order(FvsTres$pvalue),c(3,7,8)], "Fthr_vs_Thr_comp_proteins.csv")

#Now at the peptide level
Fpep_format  = parse_MSstats(Fpeps, c(40,43,44,45), "Fluorothreonine", "Peptide" )
Tpep_format  = parse_MSstats(Tpeps, c(40,43,44,45), "Threonine"      , "Peptide" )
MSSinput_pep = rbind(Fpep_format, Tpep_format) 
#quantile seems to give more reasonable distr. of log2FC
FvsTproc_pep = dataProcess(raw=MSSinput_pep, censoredInt = 0, MBimpute = TRUE, normalization = 'quantile') 
comparison1  = matrix(c(1,-1), nrow=1)
row.names(comparison1) = "AA"
FvsTquant_pep= groupComparison(contrast.matrix = comparison1, data=FvsTproc_pep)
#pull out only rows for which a comparison could be made, get the fold change and p values.
FvsTres_pep  = FvsTquant_pep$ComparisonResult[is.na(FvsTquant_pep$ComparisonResult$pvalue) == FALSE,]
FC_pep       = FvsTres_pep$log2FC
p_pep        = FvsTres_pep$pvalue
row.names(FvsTres_pep) = FvsTres_pep$Protein
write.csv(FvsTres_pep[order(FvsTres_pep$pvalue),c(3,7,8)], "Fthr_vs_Thr_comp_peptides.csv")
```

```{r}
###FILTER THE DATA
library("stringr")
library("MSstats")
protpeps           = rawpeps
#Limit scope to fully tryptic peptides.
protpeps          = protpeps[protpeps$Missed.cleavages == 0,]
#Remove hits to decoy and contaminant databases.
protpeps           = protpeps[protpeps$Reverse != "+",]
protpeps           = protpeps[protpeps$Potential.contaminant != "+",]
#Limit scope of analysis to high quality hits.
protpeps           = protpeps[protpeps$PEP <0.01,]						#a less stringent PEP will give ~20% more IDs and ~15% more proteins
#Limit scope of analysis to proteotypic peptides.
protpeps           = protpeps[protpeps$Unique..Proteins. == "yes",]
#Get row means for the pertinent rows and eliminate rows with no measured intensity.
delp0564rows      = c(40,43,44,45)-1
WTrows            = c(39,41,42,46)-1
###Extractunmodified peptides.
protpeps = protpeps[protpeps$Modifications == "Unmodified",]

parse_MSstats = function(input, cols, cond) {
tempframe = NULL
for( i in cols) {
  temp                = NULL
  ell                 = length(input[,i])
  samp                = names(input)[i]
  #Weid stuff. Need to distinguish the fluorothreonine "run" from the threonine "run"
  #when they actually originate from the same run.
  run                 = paste(samp, cond, sep = "_")
  ProteinName         = input$Proteins
  PeptideSequence     = input$Sequence
  Intensity           = input[,i]
  PrecursorCharge     = input$Charges
  FragmentIon         = rep(NA,     ell)
  ProductCharge       = rep(NA,     ell)
  IsotopeLabelType    = rep("L",    ell)
  Run                 = rep(run,    ell)
  BioReplicate        = rep(samp,   ell)
  Condition           = rep(cond,   ell)
  
  temp                = data.frame(ProteinName, PeptideSequence, 
                                   PrecursorCharge, FragmentIon, 
                                   ProductCharge, IsotopeLabelType, 
                                   Condition, BioReplicate, 
                                   Run, Intensity)
  tempframe           =rbind(temp, tempframe)
}
  return(tempframe)
}
delp0564_peps = parse_MSstats(protpeps, delp0564rows, "delp0564")
WT_peps       = parse_MSstats(protpeps, WTrows      , "WT")
diff_in       = rbind(delp0564_peps, WT_peps)
diff_assess   = dataProcess(raw = diff_in, censoredInt = 0)
comparison2   = matrix(c(1,-1), nrow=1)
row.names(comparison2) = "Strain"
diff_comp     =  groupComparison(contrast.matrix = comparison2, data=diff_assess)
groupComparisonPlots(diff_comp$ComparisonResult, type = 'VolcanoPlot')
```


```{r}

my.t.test.p.value <- function(...) {
    obj<-try(t.test(...), silent=TRUE)
    if (is(obj, "try-error")) return(NA) else return(obj$p.value)
}
mergedPeps = merge(Tpeps, Fpeps, by = "Sequence")# all=TRUE)
mergedPeps[is.na(mergedPeps)] = 0
Trows   = c(40,43,44,45)
Frows   = c(95,98,99,100)

p = c()
for (i in 1:dim(mergedPeps)[1]) {
  r    = mergedPeps[i,Frows]/(mergedPeps[i, Frows] + mergedPeps[i,Trows])
  p[i] = my.t.test.p.value(r, mu = 0.1)
}

crap = cbind(p, as.character(mergedPeps$Sequence), rowMeans(mergedPeps[,Frows]/(mergedPeps[, Frows] + mergedPeps[,Trows])))
write.csv(crap, "crap.csv")
```

```{r}
setwd("D:/jmcmurry/Documents/20160609_morph_processing_files/")
gcogs                  = read.csv("genome_COGs.txt", sep = "\t")
pcogs                  = read.csv("plasmid_COGs.txt", sep= "\t")
IDmapping              = read.csv("gene-name-comparisons.txt", sep = "\t")
allcogs                = rbind(gcogs, pcogs)
allcogs                = merge(allcogs, IDmapping, by = "SCAT_ID")
names(allcogs)[14]     = "Proteins"
Fcogs                  = merge(allcogs, Fpeps, by = "Proteins")
Tcogs                  = merge(allcogs, Tpeps, by = "Proteins")
Fcog_table             = data.frame(table(Fcogs$COGclassID))
Tcog_table             = data.frame(table(Tcogs$COGclassID))
TFcog_table            = merge(Tcog_table, Fcog_table, by = "Var1")
row.names(TFcog_table) = TFcog_table$Var1
TFcog_table            = TFcog_table[,2:3]
names(TFcog_table)     = c("Fthr peps", "Thr peps")
write.csv(TFcog_table, "FpepTpep_COGs.csv")
fishy                  = fisher.test(TFcog_table, simulate.p.value = TRUE)
fishy
```

