---
title: "proteomics2DEseq2"
author: "Jon"
date: "February 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r }


library("DESeq2")
setwd("D:/jmcmurry/Documents/20160609_morph_processing_files/")
counts = read.csv("Thr_and_Fthr_counts.csv", row.names="ID")
#counts = counts[rowSums(counts[,c(1,3,5,7)]) > 0,]
coldata = read.csv("Thr_and_Fthr_counts_conditions.csv")
dds_filt = DESeqDataSetFromMatrix(countData = counts, colData= coldata, design = ~ sample + condition)
diffy_filt = DESeq(dds_filt)
difres_filt = results(diffy_filt)


plot(difres_filt$baseMean, -difres_filt$log2FoldChange, 
log = "x",
xlab = "Mean Base Counts", ylab = "Log2 Fold Change", cex.lab = 1.5,
pch = 16, cex = 0.7,
cex.axis = 1,
xaxt = "n",
)

myTicks=c(0.5, 1, 2, 4, 8, 16, 32, 64, 128, 256)

axis(side=1,at=myTicks, 
    labels=ifelse(myTicks >= 1, sprintf("%.0f", myTicks),
sprintf("%0.1f", myTicks)))

sigup = difres_filt[difres_filt$padj < 0.05 & is.na(difres_filt$padj) == FALSE & difres_filt$log2FoldChange <0,]
sigdown = difres_filt[difres_filt$padj < 0.05 & is.na(difres_filt$padj) == FALSE & difres_filt$log2FoldChange >0,]
points(sigup$baseMean, -sigup$log2FoldChange, col =2, pch = 16, cex = .7)
points(sigdown$baseMean, -sigdown$log2FoldChange, col =4, pch = 16, cex = .7)



```